// VPS-specific PM2 config (untracked by git - survives auto-deploy resets)
module.exports = {
  apps: [
    {
      name: 'alfa-app',
      script: 'server.js',
      exec_mode: 'fork',
      cwd: '/root/alfa-option/.next/standalone/alfa-option',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
        HOSTNAME: '0.0.0.0',
        DATABASE_URL: 'file:/root/alfa-option/db/custom.db',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '700M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/root/alfa-option/logs/alfa-app-error.log',
      out_file: '/root/alfa-option/logs/alfa-app-out.log',
    },
    {
      name: 'alfa-ws',
      script: 'index.ts',
      interpreter: '/root/.bun/bin/bun',
      exec_mode: 'fork',
      cwd: '/root/alfa-option/mini-services/trading-ws',
      env: { PORT: 3003 },
      instances: 1,
      autorestart: true,
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/root/alfa-option/logs/alfa-ws-error.log',
      out_file: '/root/alfa-option/logs/alfa-ws-out.log',
    },
    {
      name: 'alfa-bridge',
      script: '/root/alfa-option/mini-services/eo-bridge/.venv/bin/python',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 3004 --log-level info',
      cwd: '/root/alfa-option/mini-services/eo-bridge',
      env: { PYTHONUNBUFFERED: '1' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '700M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/root/alfa-option/logs/alfa-bridge-error.log',
      out_file: '/root/alfa-option/logs/alfa-bridge-out.log',
    },
  ],
};
